### ISSUE TITLE
[功能建议]: 新增配置代理端口

### ISSUE THREAD

**Issue by liuhuabaobao** [zhiyu1998/nonebot-plugin-multimodal-gemini#2]
### 你的功能建议是否和某个问题相关？

需要挂tun模式才能使用

### 你希望看到什么解决方案？

配置文件新增配置代理端口

### 意向参与贡献

- [ ] 我有意向参与具体功能的开发实现并将代码贡献回到上游社区

**Comment by zhiyu1998** [comment]
这个暂时不会添加，至少近期不会，以后会考虑添加反代
