### ISSUE TITLE
[Bug]: 关键词识别错误？

### ISSUE THREAD

**Issue by liuhuabaobao** [zhiyu1998/nonebot-plugin-multimodal-gemini#3]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

偶然触发，不太确定能否复现

### 实际结果

将gemini中emini也识别为问题

### 截图或视频

[在这里上传图片]
![IMG_20241216_004557](https://github.com/user-attachments/assets/89a48d97-ec3b-4333-910e-6ec253f9babb)

### 插件版本号

0.0.4

### 适配器类型

napcat

### Python版本

Python3.9~3.12之间

### 系统

windows

**Comment by zhiyu1998** [comment]
1. Gemini关键字确实会出现这个问题， 暂时先使用小写的`gemini`，等待修复下

2. 可能是你的 prompt 太长了，这个插件用的 `base64` ，所以本身就很长，你prompt再写长一点就成傻子了
