### ISSUE TITLE
[Bug]: 私聊貌似不会回复

### ISSUE THREAD

**Issue by liuhuabaobao** [zhiyu1998/nonebot-plugin-multimodal-gemini#4]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

私聊？

### 实际结果

无反应，私聊回复中为 zhenxun 自带插件ai回复，并不是gemini回复

### 截图或视频

[在这里上传图片]
![IMG_20241216_034734](https://github.com/user-attachments/assets/fe8e9512-6115-4980-be6f-542587bcc62b)
![Screenshot_2024-12-16-03-46-08-142_com tencent mobileqq-edit](https://github.com/user-attachments/assets/64158811-183e-4991-bd5a-44a1649f20f8)

### 插件版本号

0.0.4

### 适配器类型

napcat

### Python版本

Python3.9~3.12之间

### 系统

windows

**Comment by zhiyu1998** [comment]
私聊暂时不会添加，初衷是设计一个大家一起玩的多模态，自己私聊不如使用其他 gemini 插件或者一些开源的网页，例如：

https://gemini.u14.app/
