### ISSUE TITLE
[Feat]: 添加命令和图片一起发送

### ISSUE THREAD

**Issue by liuhuabaobao** [zhiyu1998/nonebot-plugin-multimodal-gemini#5]
### 这个问题是否已经存在？

- [X] 我已经搜索过现有的问题 (https://gitee.com/../../issues)

### 如何复现

使用QQ引用图片或视频就会报错，但是如果在发送时选中图片发送并不会报错，对话也是正常

### 实际结果

引用图片或视频无反应，后台报错

### 截图或视频

[在这里上传图片]
![IMG_20241216_042345](https://github.com/user-attachments/assets/8520a975-ccdf-4084-b24d-c6074f945c83)
![Image_1734294180811](https://github.com/user-attachments/assets/f0077339-b379-453e-a963-7a51822c4597)
![Image_1734294179668](https://github.com/user-attachments/assets/2a50512b-1f87-4bcd-8f65-8f1a0afb6926)
![IMG_20241216_042246](https://github.com/user-attachments/assets/4b74e37b-6604-45b3-a588-cd2db59bd936)

### 插件版本号

0.0.4

### 适配器类型

napcat

### Python版本

Python3.9~3.12之间

### 系统

windows

**Comment by zhiyu1998** [comment]
目前 nb 版本的 gemini 多模态助手我写的还没添加指令和图片一起发送，只能单独引用消息中的图片和视频，等待后续添加

**Comment by hakunomiko** [comment]
看上去像是网络问题，试试挂点魔法看看

**Comment by liuhuabaobao** [comment]
> 看上去像是网络问题，试试挂点魔法看看

魔法有挂的，看报错我问ai也是网络问题，但是正常的询问不引用视频是能用的

**Comment by hakunomiko** [comment]
> > 看上去像是网络问题，试试挂点魔法看看
> 
> 魔法有挂的，看报错我问ai也是网络问题，但是正常的询问不引用视频是能用的

这就不太确定为啥了，Nonebot这边复现不出来，没用过真寻bot也不确定是不是有什么地方不一样......
